 /* ###########################################################################
  *
  *  JFBChat it's a simple software written in Java that let you int contact
  *  with yours Facebook friends without your browser.
  *  Copyright (C) 2011  Digitex (Giuseppe Federico)
  *
  *  This program is free software: you can redistribute it and/or modify
  *  it under the terms of the GNU General Public License as published by
  *  the Free Software Foundation, either version 3 of the License, or
  *  (at your option) any later version.
  *
  * This program is distributed in the hope that it will be useful,
  * but WITHOUT ANY WARRANTY; without even the implied warranty of
  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  * GNU General Public License for more details.
  *
  * You should have received a copy of the GNU General Public License
  * along with this program.  If not, see <http://www.gnu.org/licenses/>.
  *
  *###########################################################################
  *
  */

package jfbchat;

import org.jivesoftware.smack.XMPPConnection;

        /**
 *
 * @author peppe
 */
public class ContactPanel extends javax.swing.JPanel {
    private static int contactID = 0;


    private Contact contact;
    private Connection connection;

    /** Creates new form ContactPanel */
    public ContactPanel(Connection connection, Contact contact) {

        this.contact = contact;
        this.connection = connection;


        initComponents();

        //Init the contact username
        contactLabel.setText(contact.getUser());

        //If the contact is available check the box
        OnlineRadioBox.setSelected(contact.getPresence().isAway());
        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contactLabel = new javax.swing.JLabel();
        OnlineRadioBox = new javax.swing.JRadioButton();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        contactLabel.setText("Cotact");
        contactLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        OnlineRadioBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OnlineRadioBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(contactLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(OnlineRadioBox))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contactLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(OnlineRadioBox, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void OnlineRadioBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OnlineRadioBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OnlineRadioBoxActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        MyChatManager chatManager = connection.getChatManager();
        

        if (chatManager.add(new ChatFrame(connection, contact), contact.getID())){
            chatManager.getChat(contact.getID()).setVisible(true); //if the chat is present in the chatmanager then show it
            System.out.println(contact.getID());
        }
       else{
            chatManager.getChat(contact.getID()).setVisible(true);
            System.out.println("Reload the last chat");
            System.out.println(contact.getID());
            //TODO: make with exceptions here..
        }
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton OnlineRadioBox;
    private javax.swing.JLabel contactLabel;
    // End of variables declaration//GEN-END:variables

}
