 /* ###########################################################################
  *
  *  JFBChat it's a simple software written in Java that let you int contact
  *  with yours Facebook friends without your browser.
  *  Copyright (C) 2011  Digitex (Giuseppe Federico)
  *
  *  This program is free software: you can redistribute it and/or modify
  *  it under the terms of the GNU General Public License as published by
  *  the Free Software Foundation, either version 3 of the License, or
  *  (at your option) any later version.
  *
  * This program is distributed in the hope that it will be useful,
  * but WITHOUT ANY WARRANTY; without even the implied warranty of
  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  * GNU General Public License for more details.
  *
  * You should have received a copy of the GNU General Public License
  * along with this program.  If not, see <http://www.gnu.org/licenses/>.
  *
  *###########################################################################
  *
  */

package jfbchat;

import java.awt.Color;
import javax.swing.ImageIcon;

import jfbchat.resources.Imgs;
import jfbchat.debug.DebugMessage;

/**
 * A JPanel that represent a contact in the ContactList
 * @author Digitex (Giuseppe Federico - digtex3d@gmail.com)
 */

public class ContactPanel extends javax.swing.JPanel {

    private Contact contact;
    private Connection connection;

    /** Creates new form ContactPanel */
    public ContactPanel(Connection connection, Contact contact) {

        this.contact = contact;
        this.connection = connection;

        initComponents();

        //Init the contact username
        contactLabel.setText(contact.getUser());

        //Update the status of the contact in the JPanel
        update(contact);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contactLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        stateIcon = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        contactLabel.setBackground(new java.awt.Color(255, 255, 255));
        contactLabel.setFont(new java.awt.Font("Verdana", 1, 15)); // NOI18N
        contactLabel.setForeground(new java.awt.Color(51, 102, 204));
        contactLabel.setText("Cotact");
        contactLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        add(contactLabel);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        stateIcon.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        stateIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jfbchat/imgs/availableIcon.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(stateIcon)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(stateIcon)
                .addContainerGap())
        );

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Update the status of the contact in the JPanel
     * @param the contact associated to this JPanel
     */
  
    public void update(Contact contact){

        this.contact = contact;

        if (contact.getPresence().isAway()){

            stateIcon.setIcon(new ImageIcon(getClass().getResource(Imgs.AWAY_ICON)));
            setVisible(true);


        }else {
            if ((contact.getPresence().isAvailable())){
            stateIcon.setIcon(new ImageIcon(getClass().getResource(Imgs.AVAILABLE_ICON)));
            setVisible(true);
            }
            else{
                setVisible(false);
            }

        }
    }

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        
        if (contact.isActive()){

            //If the chat is present in the chatmanager show it.
            if (contact.getChatFrame().isVisible() == false){

                  contact.getChatFrame().setVisible(true);

                        
            }

            new DebugMessage("Contact clicked: The chat is already "
                    + "present in the chat manager");
            
        }
        else{

            /**If the chat is NOT present in the chatmanager then add it and
             * set the contact active true
             */

            contact.setActive(true);
            contact.addToChatManager();
            
        }
    }//GEN-LAST:event_formMouseClicked

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        
        this.setBackground(new Color(51,102,204));
        jPanel1.setBackground(new Color(51,102,204));

        contactLabel.setForeground(Color.white);

    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        this.setBackground(Color.white);
        jPanel1.setBackground(Color.white);
        contactLabel.setForeground(new Color(51,102,204));
    }//GEN-LAST:event_formMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contactLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel stateIcon;
    // End of variables declaration//GEN-END:variables

}
