/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BehaviorPanel.java
 *
 * Created on 11 mars 2011, 17:08:53
 */

package jfbchat.frames.preferences;

import jfbchat.resources.Options;
import jfbchat.resources.ChatPreferences;

import javax.swing.JCheckBox;

/**
 *
 * @author peppe
 */
public class BehaviorPanel extends javax.swing.JPanel {

    private ChatPreferences prefs;

    /** Creates new form BehaviorPanel */
    public BehaviorPanel() {
        initComponents();

        prefs = new  ChatPreferences();
        //Init the options
        CheckDownloadAvatar.setSelected( prefs.getPreferences().getBoolean( Options.DownloadImgs, true ) );

        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CheckDownloadAvatar = new javax.swing.JCheckBox();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Avatars"));

        CheckDownloadAvatar.setText("Download avatars");
        CheckDownloadAvatar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CheckDownloadAvatarItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CheckDownloadAvatar)
                .addContainerGap(200, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(CheckDownloadAvatar)
                .addContainerGap(225, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CheckDownloadAvatarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CheckDownloadAvatarItemStateChanged

        //Get the item
        JCheckBox item = (JCheckBox) evt.getItem();

        //Change the value in the preferences with the value of the checkbox
        prefs.getPreferences().putBoolean(Options.DownloadImgs, item.isSelected());

    }//GEN-LAST:event_CheckDownloadAvatarItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckDownloadAvatar;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
