/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NotificationsPanel.java
 *
 * Created on 10 mars 2011, 16:10:29
 */

package jfbchat.frames.preferences;

import jfbchat.resources.Options;
import jfbchat.resources.ChatPreferences;

import javax.swing.JCheckBox;
/**
 *
 * @author peppe
 */
public class NotificationsPanel extends javax.swing.JPanel {

    private ChatPreferences prefs;

    /** Creates new form NotificationsPanel */
    public NotificationsPanel() {
        initComponents();

        //Init the preferences
        prefs = new ChatPreferences();

        //Init the options
        CheckEnableIncomingMsgSnd.setSelected( prefs.getPreferences().getBoolean( Options.INCOMING_SOUND, true ) );
        CheckSendedMsgSnd.setSelected( prefs.getPreferences().getBoolean( Options.SENDED_SOUND, true ) );
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CheckEnableIncomingMsgSnd = new javax.swing.JCheckBox();
        CheckSendedMsgSnd = new javax.swing.JCheckBox();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Sounds"));

        CheckEnableIncomingMsgSnd.setText("Notification sound for incoming messages");
        CheckEnableIncomingMsgSnd.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CheckEnableIncomingMsgSndItemStateChanged(evt);
            }
        });

        CheckSendedMsgSnd.setText("Notification sound for sended messages");
        CheckSendedMsgSnd.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CheckSendedMsgSndItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CheckEnableIncomingMsgSnd)
                    .addComponent(CheckSendedMsgSnd))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(CheckEnableIncomingMsgSnd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CheckSendedMsgSnd)
                .addGap(207, 207, 207))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CheckEnableIncomingMsgSndItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CheckEnableIncomingMsgSndItemStateChanged
        
        //Get the item
        JCheckBox item = (JCheckBox) evt.getItem();

        //Change the value in the preferences with the value of the checkbox
        prefs.getPreferences().putBoolean(Options.INCOMING_SOUND, item.isSelected());



    }//GEN-LAST:event_CheckEnableIncomingMsgSndItemStateChanged

    private void CheckSendedMsgSndItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CheckSendedMsgSndItemStateChanged
        //Get the item
        JCheckBox item = (JCheckBox) evt.getItem();

        //Change the value in the preferences with the value of the checkbox
        prefs.getPreferences().putBoolean(Options.SENDED_SOUND, item.isSelected());
    }//GEN-LAST:event_CheckSendedMsgSndItemStateChanged

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckEnableIncomingMsgSnd;
    private javax.swing.JCheckBox CheckSendedMsgSnd;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
