/*
   To change this template, choose Tools | Templates
   and open the template in the editor.
*/

/*
   PanelTypingMessage.java

   Created on 16 mars 2011, 20:47:54
*/

package jfbchat.panels;

/**

   @author peppe
*/
public class PanelTypingMessage extends javax.swing.JPanel {

  private final int MAX_DIMENSION = 32767;

  /** Creates new form PanelTypingMessage */
  public PanelTypingMessage(String contactName) {
    initComponents();
    jLabelMessage.setText(contactName + " is typing...");
  }

  /** This method is called from within the constructor to
    initialize the form.
    WARNING: Do NOT modify this code. The content of this method is
    always regenerated by the Form Editor.
  */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">// GEN-BEGIN:initComponents
  private void initComponents() {
    jLabelMessage = new javax.swing.JLabel();
    setBackground(new java.awt.Color(255, 255, 255));
    jLabelMessage.setBackground(new java.awt.Color(208, 239, 238));
    jLabelMessage.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
    jLabelMessage.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    jLabelMessage.setText("Message");
    jLabelMessage.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
    jLabelMessage.setAlignmentY(0.0F);
    jLabelMessage.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jLabelMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                    Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jLabelMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                    Short.MAX_VALUE)
    );
  }// </editor-fold>// GEN-END:initComponents

  /**
    This method fix the layout of the message and set the maximum Height
    @return
  */
  @Override
  public java.awt.Dimension getMaximumSize() {
    int fixed_height = (int) getPreferredSize().getHeight();
    java.awt.Dimension fixedDimension;
    fixedDimension = new java.awt.Dimension(MAX_DIMENSION , fixed_height);
    return fixedDimension;
  }

  // Variables declaration - do not modify// GEN-BEGIN:variables
  private javax.swing.JLabel jLabelMessage;
  // End of variables declaration// GEN-END:variables

}
