/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelGroup.java
 *
 * Created on 28 févr. 2011, 20:59:32
 */

package jfbchat.panels;

import jfbchat.Group;
import jfbchat.resources.*;

/**
 *  A Panel with the associated group name
 * 
 * @author Digitex ( Giuseppe Federico - digitex3d@gmail.com)
 */
public class PanelGroup extends javax.swing.JPanel {

    private final int MAX_DIMENSION = 32767;
    private Group group;
    private ChatPreferences prefs;

    /** Creates new form PanelGroup */
    public PanelGroup(String name, Group group) {
        initComponents();

        this.prefs = new ChatPreferences();

        jLabelGroupName.setText(name);
        this.group = group;
        updatePanel();

    }

    public void updatePanel(){

        if( this.prefs.getPreferences().getBoolean(Options.SHOW_EMPTY_GROUPS, false) ){

            this.collapseGroupLabel.setVisible( group.hasConnectedContacts() );
            this.setVisible(true);
            
        }
        else{
                this.setVisible(group.hasConnectedContacts());
            }
        }

    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabelGroupName = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        collapseGroupLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(230, 255, 255));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jPanelMain.setBackground(new java.awt.Color(208, 239, 238));

        jPanel3.setBackground(new java.awt.Color(208, 239, 238));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jLabelGroupName.setBackground(new java.awt.Color(136, 136, 136));
        jLabelGroupName.setFont(new java.awt.Font("Verdana", 1, 15));
        jLabelGroupName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelGroupName.setText("groupName");
        jPanel3.add(jLabelGroupName);

        jPanel1.setBackground(new java.awt.Color(208, 239, 238));

        collapseGroupLabel.setBackground(new java.awt.Color(208, 239, 238));
        collapseGroupLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        collapseGroupLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        collapseGroupLabel.setText(" - ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(collapseGroupLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(collapseGroupLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addGap(77, 77, 77)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(jPanelMain);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked

        if (this.group.isVisible()){

            this.collapseGroupLabel.setText(" + ");
            this.group.hideContacts();

        }else{
            this.collapseGroupLabel.setText(" - ");
            this.group.showContacts();

        }
            

    }//GEN-LAST:event_formMouseClicked

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked

       if (this.group.isVisible()){

            this.collapseGroupLabel.setText(" + ");
            this.group.hideContacts();

        }else{
            this.collapseGroupLabel.setText(" - ");
            this.group.showContacts();

        }
    }//GEN-LAST:event_jPanel3MouseClicked

    /**
     * This method fix the layout of the message and set the maximum Height
     * @return
     */
    @Override
    public java.awt.Dimension getMaximumSize() {

        int fixed_height = (int) getPreferredSize().getHeight();
        java.awt.Dimension fixedDimension;

        fixedDimension = new java.awt.Dimension( MAX_DIMENSION ,fixed_height);

        return fixedDimension;

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel collapseGroupLabel;
    private javax.swing.JLabel jLabelGroupName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelMain;
    // End of variables declaration//GEN-END:variables

}
