 /* ###########################################################################
  *
  *  JFBChat it's a simple software written in Java that let you int contact
  *  with yours Facebook friends without your browser.
  *  Copyright (C) 2011  Digitex (Giuseppe Federico)
  *
  *  This program is free software: you can redistribute it and/or modify
  *  it under the terms of the GNU General Public License as published by
  *  the Free Software Foundation, either version 3 of the License, or
  *  (at your option) any later version.
  *
  * This program is distributed in the hope that it will be useful,
  * but WITHOUT ANY WARRANTY; without even the implied warranty of
  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  * GNU General Public License for more details.
  *
  * You should have received a copy of the GNU General Public License
  * along with this program.  If not, see <http://www.gnu.org/licenses/>.
  *
  *###########################################################################
  *
  */

package jfbchat.panels;


import java.util.Date;
import java.text.SimpleDateFormat;

import jfbchat.Contact;

import jfbchat.resources.*;

import jfbchat.debug.DebugMessage;


 /**
 * A JPanel that represent a incoming/sended message in the ChatFrame
 * @author Digitex ( Giuseppe Federico - digitex3d@gmail.com )
 */

public class PanelMessage extends javax.swing.JPanel {

    private Date hour = new Date();
    private SimpleDateFormat formatter;
    private String formattedHour;

    private MP3 incomingSnd;
    private MP3 sendSnd;
    private ChatPreferences prefs;
    

    /** Creates new messages form PanelMessage */
    public PanelMessage(boolean send,Contact contact, String text) {
        
        //Time
        this.formatter = new SimpleDateFormat("HH:mm");
        this.formattedHour = formatter.format(hour);

        //Init the JPanel components
        initComponents();

        //Init the chat preferences
        this.prefs = new ChatPreferences();

        //Load the incoming message sound
        try {

            incomingSnd = new MP3( Snds.INCOMING );
            
        } catch (Exception e)

        {

            new DebugMessage(this.getClass(), "Cannot load" + Snds.INCOMING );

        }

        //Load the sended message sound
        try {

            sendSnd = new MP3( Snds.SENDED );

        } catch (Exception e)

        {

            new DebugMessage(this.getClass(), "Cannot load" + Snds.SENDED );

        }

        if (send){

            Labelfromto.setText(formattedHour + " Me: ");
            
            //If SENDED_SOUND is enabled play a sound
            if( prefs.getPreferences().getBoolean( ( Options.SENDED_SOUND ), true ) ){
                sendSnd.play();
            }


        }
        else{
            if(text == null){
                Labelfromto.setText(contact.getUser() + " is typing...");
            }else{

                Labelfromto.setText(formattedHour + " " +contact.getUser() + " says: ");

                //If INCOMING_SOUND is enabled play a sound
                 if( prefs.getPreferences().getBoolean( ( Options.INCOMING_SOUND ), true ) ){
                    incomingSnd.play();
                }
            }
        }
            
            
        //Change the panel text
        LabelText.setText(text);
       
       
        setVisible(true);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelMain = new javax.swing.JPanel();
        jPanelTextField = new javax.swing.JPanel();
        LabelText = new javax.swing.JTextPane();
        jPanelFromTo = new javax.swing.JPanel();
        Labelfromto = new javax.swing.JLabel();

        setBackground(new java.awt.Color(254, 254, 254));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanelMain.setBackground(new java.awt.Color(255, 255, 255));

        jPanelTextField.setBackground(new java.awt.Color(255, 255, 255));

        LabelText.setBackground(new java.awt.Color(255, 255, 255));
        LabelText.setEditable(false);
        LabelText.setText("Message here");

        javax.swing.GroupLayout jPanelTextFieldLayout = new javax.swing.GroupLayout(jPanelTextField);
        jPanelTextField.setLayout(jPanelTextFieldLayout);
        jPanelTextFieldLayout.setHorizontalGroup(
            jPanelTextFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
        );
        jPanelTextFieldLayout.setVerticalGroup(
            jPanelTextFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelText)
        );

        jPanelFromTo.setBackground(new java.awt.Color(208, 239, 238));

        Labelfromto.setBackground(new java.awt.Color(208, 239, 238));
        Labelfromto.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        Labelfromto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Labelfromto.setText("... say: / me:");
        Labelfromto.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Labelfromto.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Labelfromto.setMaximumSize(new java.awt.Dimension(3780, 13338));

        javax.swing.GroupLayout jPanelFromToLayout = new javax.swing.GroupLayout(jPanelFromTo);
        jPanelFromTo.setLayout(jPanelFromToLayout);
        jPanelFromToLayout.setHorizontalGroup(
            jPanelFromToLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Labelfromto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
        );
        jPanelFromToLayout.setVerticalGroup(
            jPanelFromToLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Labelfromto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFromTo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addComponent(jPanelFromTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 134, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents
    
   
   


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane LabelText;
    private javax.swing.JLabel Labelfromto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelFromTo;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelTextField;
    // End of variables declaration//GEN-END:variables

}
