/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelNotification.java
 *
 * Created on Jun 17, 2011, 4:43:45 PM
 */
package jfbchat.panels;

import java.awt.*;
import javax.swing.*;

import jfbchat.resources.Imgs;
/**
 *
 * @author peppe
 */
public class PanelNotification extends javax.swing.JPanel {
  private Image background;

  public PanelNotification() {
  initComponents();

  //The background image
  this.background = new ImageIcon(getClass().getResource(Imgs.NOTIFICATION_PANEL)).getImage();
  }

  @Override
  public void update(Graphics g) {
  // override this to do nothing, no background fill is needed
  }

  @Override
  public void paintComponent(Graphics g) {
  g.drawImage(this.background, 0, 0, getSize().width, getSize().height, this);

  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

  javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
  this.setLayout(layout);
  layout.setHorizontalGroup(
    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGap(0, 191, Short.MAX_VALUE)
);
  layout.setVerticalGroup(
    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGap(0, 120, Short.MAX_VALUE)
);
  }// </editor-fold>//GEN-END:initComponents
  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables
}
