/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelGroup.java
 *
 * Created on 28 févr. 2011, 20:59:32
 */

package jfbchat.panels;

import jfbchat.Group;
import jfbchat.resources.*;

/**
 *
 * @author peppe
 */
public class PanelGroup extends javax.swing.JPanel {

    private Group group;
    private ChatPreferences prefs;

    /** Creates new form PanelGroup */
    public PanelGroup(String name, Group group) {
        initComponents();

        this.prefs = new ChatPreferences();

        jLabelGroupName.setText(name);
        this.group = group;
        updatePanel();

    }

    public void updatePanel(){

        if( this.prefs.getPreferences().getBoolean(Options.SHOW_EMPTY_GROUPS, false) ){

            this.collapseGroupLabel.setVisible( group.hasConnectedContacts() );
            this.setVisible(true);
            
        }
        else{
                this.setVisible(group.hasConnectedContacts());
            }
        }

    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        collapseGroupLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelGroupName = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        collapseGroupLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        collapseGroupLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        collapseGroupLabel.setText(" - ");
        jPanel3.add(collapseGroupLabel);

        add(jPanel3);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jLabelGroupName.setBackground(new java.awt.Color(136, 136, 136));
        jLabelGroupName.setFont(new java.awt.Font("Verdana", 1, 15)); // NOI18N
        jLabelGroupName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelGroupName.setText("groupName");
        jPanel1.add(jLabelGroupName);

        add(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jPanel2);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked

        
            

    }//GEN-LAST:event_formMouseClicked

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked

       if (this.group.isVisible()){

            this.collapseGroupLabel.setText(" + ");
            this.group.hideContacts();

        }else{
            this.collapseGroupLabel.setText(" - ");
            this.group.showContacts();

        }
    }//GEN-LAST:event_jPanel3MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel collapseGroupLabel;
    private javax.swing.JLabel jLabelGroupName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

}
